// DO NOT EDIT. Generated by internal/gen/plugins/generator.go.
package main

import (
	"strings"

	_ "github.com/caddy-dns/ionos"
	"github.com/liujed/dns01proxy"
	"github.com/liujed/dns01proxy/cmd"
)

// Work around https://github.com/golang/go/issues/29228.
var version = ""
var commit = ""

func init() {
	if version == "" && commit == "" {
		return
	}

	buf := strings.Builder{}
	if version != "" {
		if !strings.HasPrefix(version, "v") {
			buf.WriteRune('v')
		}
		buf.WriteString(version)

		if commit != "" {
			buf.WriteRune(' ')
		}
	}
	if commit != "" {
		buf.WriteRune('(')
		buf.WriteString(commit)
		buf.WriteRune(')')
	}

	dns01proxy.FallbackVersion = buf.String()
}

func main() {
	cmd.Execute()
}
